### ISSUE TITLE
mypy 0.930 breaks the sqlmypy plugin with an INTERNAL ERROR

### ISSUE THREAD

**Issue by plankthom** [dropbox/sqlalchemy-stubs#232]
Upgrading to mypy 0.930 triggered the following INTERNAL ERROR issue:
```
% mypy --config-file pkg/tsa-repo-db-client/setup.cfg -p tsa.repo.db --show-traceback
***/pkg/tsa-repo-db-client/tsa/repo/db/model.py:11: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.930
Traceback (most recent call last):
  File "mypy/semanal.py", line 5132, in accept
  File "mypy/nodes.py", line 1140, in accept
  File "mypy/semanal.py", line 2110, in visit_assignment_stmt
  File "mypy/semanal.py", line 2392, in apply_dynamic_class_hook
  File "***/miniconda3/envs/tsa37/lib/python3.7/site-packages/sqlmypy.py", line 203, in decl_info_hook
    obj = ctx.api.builtin_type('builtins.object')
AttributeError: 'SemanticAnalyzer' object has no attribute 'builtin_type'
***/pkg/tsa-repo-db-client/tsa/repo/db/model.py:11: : note: use --pdb to drop into pdb
```
Considering the announcement in https://github.com/python/mypy/issues/6617 , I assume this should be solved here ...

Workaround: keep mypy pinned on version 0.921

**Comment by plankthom** [comment]
Removal of `SemanticAnalyzer.builtin_type` :
https://github.com/python/mypy/compare/v0.921...v0.930#diff-6d2a87e2b0fdefc2766ed8e178d16253286bc574ee6798df140f081941bc5746

**Comment by 97littleleaf11** [comment]
Sorry that I forgot to update the announcement. Currently please use `named_type` instead.

**Comment by ilevkivskyi** [comment]
Could someone please submit a PR for this? (using a `hasattr()` for compatibility) Sorry, but I don't have much time to work on this myself.

**Comment by JukkaL** [comment]
I should be able to take care of this, but I don't access to the PyPI project. 

@ilevkivskyi Could you make me a maintainer at https://pypi.org/project/sqlalchemy-stubs/?

**Comment by JukkaL** [comment]
Alternatively, I wonder if we could (or should) add back `builtin_type` as an alias to `named_type`, but mark it as deprecated.

**Comment by ilevkivskyi** [comment]
IIUC this should now work with mypy 0.931, so I am closing this issue.

**Comment by ilevkivskyi** [comment]
Actually, we can still switch to the newer "official" API method, so re-opening again. PRs are welcome :-)

**Comment by JukkaL** [comment]
I have no plans to remove `builtin_type`. Keeping it around is not a significant burden.

**Comment by ilevkivskyi** [comment]
@shawnwall Essentially, yes. We can have this just in case (but since Jukka says it will be there, it is not a priority).
